{
 "title": "[Example] products service overview",
 "tags": [
  "products",
  "generated"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "logs_filter", "label": "Logs filter" },
   {
    "name": "logs_level",
    "label": "Logs level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "app_infos{service=\"products\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": {
    "content": "Manages the products catalog and stocks"
   }
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({service=\"products\", level=~\"$logs_level\"} |~ \"$logs_filter\" [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "gRPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{service=\"products\"}[$__rate_interval])",
     "legendFormat": "{{ grpc_method }} – {{ grpc_code }}"
    }
   ]
  },
  {
   "title": "gRPC Requests latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handling_seconds_bucket{service=\"products\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{service=\"products\", source=\"grpc\", level=~\"$logs_level\"} |~ \"$logs_filter\"",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{service=\"products\"}[$__rate_interval])",
     "legendFormat": "{{code}} - {{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "HTTP Requests latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_duration_seconds_bucket{service=\"products\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{service=\"products\", source=\"http\", level=~\"$logs_level\"} |~ \"$logs_filter\"",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}